### ISSUE TITLE
Segmentation violation on modrinth export

### ISSUE THREAD

**Issue by CrimsonFork** [packwiz/packwiz#144]
```
$ ./packwiz modrinth export
Loading modpack...
Refreshing index... 100 % [========================================================================] done
Reading external files...
Retrieving 79 external files...
Disclaimer: you are responsible for ensuring you comply with ALL the licenses, or obtain appropriate permissions, for the files "added to zip" below
packwiz is currently unable to match metadata between mod sites - if any of these are available from Modrinth you should change them to use Modrinth metadata (e.g. by reinstalling them using the mr commands)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x83ad58]

goroutine 1 [running]:
github.com/packwiz/packwiz/core.CreateDownloadSession({0xc0000e6500, 0x4f, 0x979efa?}, {0xc000390d80, 0x3, 0x3})
	/home/runner/work/packwiz/packwiz/core/download.go:613 +0xfd8
github.com/packwiz/packwiz/modrinth.glob..func1(0xd322c0?, {0xd6c570?, 0x0?, 0x0?})
	/home/runner/work/packwiz/packwiz/modrinth/export.go:97 +0xa1f
github.com/spf13/cobra.(*Command).execute(0xd322c0, {0xd6c570, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xd30c40)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/packwiz/packwiz/cmd.Execute()
	/home/runner/work/packwiz/packwiz/cmd/root.go:25 +0x25
main.main()
	/home/runner/work/packwiz/packwiz/main.go:12 +0x17
```

**Comment by comp500** [comment]
Could you send the modpack (or file, if you can identify it) that causes the crash? Also make sure your installation of packwiz is up to date.

**Comment by CrimsonFork** [comment]
Welp now it works suddenly. Not sure what happened, I think I didn't even restart my computer. Though yesterday it seems Curseforge was having with their serves so maybe that somehow played into it.

[This](https://gitlab.com/CrimsonFork/uwu-mc/-/tree/7a827f051c912ba3a69445c3e45c88cc2e94d09d/packwiz-data) would have been the state of the modpack at the time, in case you want to look at it, but I can't recreate the behavior anymore.

Sorry for the disturbance, I'll close the issue
