### ISSUE TITLE
 Update process failed: Token recognition error

### ISSUE THREAD

**Issue by filcuk** [packwiz/packwiz#165]
I can't start the server using latest [itzg/docker-minecraft-server](https://github.com/itzg/docker-minecraft-server/).
I have followed instructions for packwiz using git, added `.gitattributes` and run `git add --renormalize .`.
I also tried reinitialising packiwz.

Would anyone know why I'm getting this error?
My [pack.toml](https://github.com/filcuk/fimc-vanilla-plus/blob/v1.0.0-rc.4/pack.toml)

```
[init] Changing uid of minecraft to 1044
[init] Changing gid of minecraft to 65539
[init] Running as uid=1044 gid=65539 with /data as 'drwx-w---- 1 1044 1000 556 Nov 25 18:48 /data'
[init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
[init] Autopause functionality enabled
[init] Updated rcon port in knockd config
[init] Resolving type given FABRIC
[init] Checking Fabric Launcher version information.
[init] Checking Fabric Loader version information.
[init] Running packwiz installer against URL: https://github.com/filcuk/fimc-vanilla-plus/blob/v1.0.0-rc.4/pack.toml
packwiz-installer was started without packwiz-installer-bootstrap. Use the bootstrapper for automatic updates! (Disregard this message if you have your own update mechanism)
Loading manifest file...
Loading pack file...
[FATAL] Update process failed: 
ParseError(errorDescription=token recognition error at: '<', line=8, cause=LexerNoViableAltException('<'))
	at cc.ekblad.toml.serialization.TomlErrorListener.syntaxError(SourceFile:21)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(SourceFile:41)
	at org.antlr.v4.runtime.Lexer.notifyListeners(SourceFile:364)
	at org.antlr.v4.runtime.Lexer.nextToken(SourceFile:144)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(SourceFile:169)
	at org.antlr.v4.runtime.BufferedTokenStream.sync(SourceFile:152)
	at org.antlr.v4.runtime.BufferedTokenStream.consume(SourceFile:136)
	at org.antlr.v4.runtime.Parser.consume(SourceFile:570)
	at org.antlr.v4.runtime.Parser.match(SourceFile:204)
	at cc.ekblad.toml.parser.TomlParser.document(SourceFile:151)
	at cc.ekblad.toml.serialization.TomlDeserializerKt.from(SourceFile:49)
	at cc.ekblad.toml.serialization.TomlDeserializerKt.from(SourceFile:28)
	at link.infra.packwiz.installer.UpdateManager.start(SourceFile:489)
	at link.infra.packwiz.installer.UpdateManager.<init>(SourceFile:43)
	at link.infra.packwiz.installer.Main.startup(SourceFile:109)
	at link.infra.packwiz.installer.Main.<init>(SourceFile:150)
	at link.infra.packwiz.installer.Main$Companion.main(SourceFile:142)
	at link.infra.packwiz.installer.Main.main(SourceFile)
Caused by: LexerNoViableAltException('<')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(SourceFile:309)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(SourceFile:230)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(SourceFile:114)
	at org.antlr.v4.runtime.Lexer.nextToken(SourceFile:141)
	... 14 more
[init] ERROR failed to run packwiz installer
```

**Comment by copygirl** [comment]
Could it be that you want to use `https://raw.githubusercontent.com/filcuk/fimc-vanilla-plus/v1.0.0-rc.4/pack.toml` instead of `https://github.com/filcuk/fimc-vanilla-plus/blob/v1.0.0-rc.4/pack.toml`? When packwiz tries to download the latter it will get a bunch of HTML instead of the pack.toml you want it to look for, resulting in it failing to parse the file.

**Comment by filcuk** [comment]
That would be it... thank you :)

**Comment by NoicTheBrave** [comment]
What do we do if, in my case, I used https://github.com/NoicTheBrave/UMS4_0_2-BareBones/blob/main/pack.toml inside of there, and it still did not work? The corresponding index.toml (https://github.com/NoicTheBrave/UMS4_0_2-BareBones/blob/main/index.toml) is in the same folder (not sure if that is even relevant here, but just something to note) 

The pre-launch command: 
'"$INST_JAVA" -jar packwiz-installer-bootstrap.jar https://github.com/NoicTheBrave/UMS4_0_2-BareBones/blob/main/pack.toml'

The report that follows: 

`Running Pre-Launch command: C:/Program Files/Java/jre1.8.0_331/bin/javaw.exe -jar packwiz-installer-bootstrap.jar https://github.com/NoicTheBrave/UMS4_0_2-BareBones/blob/main/pack.toml
Current version is: v0.5.14
New version is: v0.5.14
Already up to date!
Loading manifest file...
Loading pack file...
[FATAL] Update process failed: 
ParseError(errorDescription=token recognition error at: '<', line=7, cause=LexerNoViableAltException('<'))
	at cc.ekblad.toml.serialization.TomlErrorListener.syntaxError(SourceFile:21)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(SourceFile:41)
	at org.antlr.v4.runtime.Lexer.notifyListeners(SourceFile:364)
	at org.antlr.v4.runtime.Lexer.nextToken(SourceFile:144)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(SourceFile:169)
	at org.antlr.v4.runtime.BufferedTokenStream.sync(SourceFile:152)
	at org.antlr.v4.runtime.BufferedTokenStream.consume(SourceFile:136)
	at org.antlr.v4.runtime.Parser.consume(SourceFile:570)
	at org.antlr.v4.runtime.Parser.match(SourceFile:204)
	at cc.ekblad.toml.parser.TomlParser.document(SourceFile:151)
	at cc.ekblad.toml.serialization.TomlDeserializerKt.from(SourceFile:49)
	at cc.ekblad.toml.serialization.TomlDeserializerKt.from(SourceFile:28)
	at link.infra.packwiz.installer.UpdateManager.start(SourceFile:488)
	at link.infra.packwiz.installer.UpdateManager.<init>(SourceFile:42)
	at link.infra.packwiz.installer.Main.startup(SourceFile:112)
	at link.infra.packwiz.installer.Main.<init>(SourceFile:154)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at link.infra.packwiz.installer.bootstrap.LoadJAR.start(LoadJAR.java:51)
	at link.infra.packwiz.installer.bootstrap.Main.<init>(Main.java:91)
	at link.infra.packwiz.installer.bootstrap.Main.main(Main.java:46)
Caused by: LexerNoViableAltException('<')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(SourceFile:309)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(SourceFile:230)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(SourceFile:114)
	at org.antlr.v4.runtime.Lexer.nextToken(SourceFile:141)
	... 19 more
User selected to quit, exiting with code 1...
Process exited with code 1.
Pre-Launch command failed with code 1.`


Any help would be appreciated

**Comment by copygirl** [comment]
Again, if you use the URL https://github.com/NoicTheBrave/UMS4_0_2-BareBones/blob/main/pack.toml, you get a web page, not the raw contents of the file, so packwiz downloads the .html file instead of the .toml file that's visually embedded somewhere within.

Click the "Raw" button on the right of the page, then copy that page URL and use it instead.
![image](https://github.com/user-attachments/assets/5b6f7545-f227-447a-9e6b-c775fce11211)
