### ISSUE TITLE
Cannot load Packwiz modpack in prism

### ISSUE THREAD

**Issue by walksanatora** [packwiz/packwiz#213]
Packwiz: AUR packwiz-git `r283.7de26ec-1`
Prism: PrismLauncher 6.3
when I expory my pack with `packwiz mr export` and try to run it in prism, no mods are downloaded and it hangs untill either I abort it or it crashes with
```
Exception caught from launcher
java.lang.ClassNotFoundException: org.quiltmc.loader.impl.launch.knot.KnotClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:151)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Exiting with ERROR
Process exited with code 2.
```

**Comment by walksanatora** [comment]
[modrinth.index.json.txt](https://github.com/packwiz/packwiz/files/11258485/modrinth.index.json.txt)
is the index.json generated

**Comment by walksanatora** [comment]
tried to recreate the pack using fabric (which means I had to drop a mod)
prism still did not download the mods from the mrpack

**Comment by walksanatora** [comment]
quilt does not like tor proxy
