### ISSUE TITLE
`panic: runtime error: index out of range [6] with length 6` when installing or updating CurseForge mod

### ISSUE THREAD

**Issue by ullebe1** [packwiz/packwiz#246]
I'm experiencing the following error whenever I try installing or updating a CurseForge mod:

```
❯ packwiz curseforge install https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map
Looking up CurseForge slug...
panic: runtime error: index out of range [6] with length 6

goroutine 1 [running]:
github.com/packwiz/packwiz/curseforge.filterLoaderTypeIndex(...)
	/home/runner/work/packwiz/packwiz/curseforge/curseforge.go:256
github.com/packwiz/packwiz/curseforge.findLatestFile({{0xc00013e108, 0x11}, {0xc00024e000, 0x77}, {0xc0001dcef0, 0x10}, 0x4d954, 0x1b0, 0x1a7, 0x6, ...}, ...)
	/home/runner/work/packwiz/packwiz/curseforge/curseforge.go:327 +0x3a6
github.com/packwiz/packwiz/curseforge.getLatestFile({{0xc00013e108, 0x11}, {0xc00024e000, 0x77}, {0xc0001dcef0, 0x10}, 0x4d954, 0x1b0, 0x1a7, 0x6, ...}, ...)
	/home/runner/work/packwiz/packwiz/curseforge/install.go:420 +0x145
github.com/packwiz/packwiz/curseforge.glob..func4(0xdb5f80?, {0xc000270520?, 0x1, 0x1})
	/home/runner/work/packwiz/packwiz/curseforge/install.go:123 +0x10cc
github.com/spf13/cobra.(*Command).execute(0xdb5f80, {0xc0002704f0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xdb4880)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/packwiz/packwiz/cmd.Execute()
	/home/runner/work/packwiz/packwiz/cmd/root.go:25 +0x25
main.main()
	/home/runner/work/packwiz/packwiz/main.go:15 +0x17](panic: runtime error: index out of range [6] with length 6)
```

**Comment by ullebe1** [comment]
Turns out I was using an outdated version, sorry for the noise.
